#!/usr/bin/env bash
# gen-test-profiles.sh - (re)generate tests/generated/ from profiles/.
#
# Every production profile gets a test twin at the same relative path (profiles/70-gnome.yaml ->
# tests/generated/70-gnome.yaml, profiles/optional/obs.yaml -> tests/generated/optional/obs.yaml). The twin is
# the production profile 1:1 minus whatever halts or pauses a run (prompt-logout / requires-new-shell restart
# policies, interrupt / manual / shell-reload steps, confirm guards); relative config paths become absolute.
# Each generated file starts with a comment listing exactly what was changed. See tests/lib/gen_test_profiles.py.
#
# tests/generated/ is git-ignored: it is derived data, regenerated by bootstrap.sh --test and tests/run-tests.sh
# before every use, so it can never drift from profiles/.
#
#   tests/gen-test-profiles.sh            # write tests/generated/ (only files whose content changed)
#   tests/gen-test-profiles.sh --check    # exit 1 and show a diff when tests/generated/ is out of date
#   tests/gen-test-profiles.sh --quiet    # no per-file output
#   tests/gen-test-profiles.sh --container   # container variant (also TEST_CONTEXT=container): drop the steps
#                                            # that need systemd/snapd, listed in tests/generated/container-skips.tsv
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
OUT_DIR="$REPO_DIR/tests/generated"

args=()
for a in "$@"; do
    case "$a" in
        --check | --quiet | --container) args+=("$a") ;;
        -h | --help)
            sed -n '2,19p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            echo "unknown argument: $a" >&2
            exit 2
            ;;
    esac
done

if ! python3 -c 'import yaml' 2>/dev/null; then
    echo "gen-test-profiles: python3 with PyYAML is required (sudo apt install -y python3-yaml)" >&2
    exit 1
fi

exec python3 "$REPO_DIR/tests/lib/gen_test_profiles.py" "$REPO_DIR" "$OUT_DIR" "${args[@]}"
